### ISSUE TITLE
`nixVulkanNvidia` failling when building with `No such file or directory` error

### ISSUE THREAD

**Issue by Player-205** [guibou/nixGL#96]
```sh
> nix-env -iA nixgl.auto.nixVulkanNvidia --argstr nvidiaVersion 495.46
installing 'nixVulkanNvidia-495.46'
this derivation will be built:
  /nix/store/cw30j419zmbhd1glia6539vwg6ssq5j5-nixVulkanNvidia-495.46.drv
building '/nix/store/cw30j419zmbhd1glia6539vwg6ssq5j5-nixVulkanNvidia-495.46.drv'...
ls: cannot access '/nix/store/36hkib0km5czabqbj7rvprwcvbdazmk1-nvidia-x11-510.54/share/vulkan/icd.d/nvidia_icd.json': No such file or directory
File /nix/store/36hkib0km5czabqbj7rvprwcvbdazmk1-nvidia-x11-510.54/share/vulkan/icd.d/nvidia_icd.json, referenced in /nix/store/blhnssdsvsic5jid876vvbfv58whm6gn-nixVulkanNvidia-495.46/bin/nixVulkanNvidia-495.46 does not exists.
error: builder for '/nix/store/cw30j419zmbhd1glia6539vwg6ssq5j5-nixVulkanNvidia-495.46.drv' failed with exit code 255```

**Comment by guibou** [comment]
Thank you for the report. This should be fixed now, could you test and tell me if it is ok for you?

**Comment by Player-205** [comment]
Sorry, but I switched from ubuntu to nixos over this time and now all GPU drivers work natively.

**Comment by blurgyy** [comment]
Hi, I think the issue is still present, I get the following error:

```log
$ nix build --impure
warning: Git tree '/tmp/rwwtt' is dirty
error: builder for '/nix/store/qgjbzpi2wghyf7mv3bn3bydkvfld32ji-nixVulkanNvidia-515.48.07.drv' failed with exit code 255;
       last 2 log lines:
       > ls: cannot access '/nix/store/61cw28zk1s7qfh825ldg8if7x68qfr2r-nvidia-x11-515.48.07-nixGL/share/vulkan/icd.d/nvidia_icd.json': No such file or directory
       > File /nix/store/61cw28zk1s7qfh825ldg8if7x68qfr2r-nvidia-x11-515.48.07-nixGL/share/vulkan/icd.d/nvidia_icd.json, referenced in /nix/store/35fyq4qwg7zkj12r7zmwfd5sxizp0k49-nixVulkanNvidia-515.48.07/bin/nixVulkanNvidia-515.48.07 does not exists.
       For full logs, run 'nix log /nix/store/qgjbzpi2wghyf7mv3bn3bydkvfld32ji-nixVulkanNvidia-515.48.07.drv'.
error: 1 dependencies of derivation '/nix/store/ga9wjzvk22k6mw58p2ml20b29rhng1vv-rwwtt.drv' failed to build
```

The directory which `ls` complains about has a file called `nvidia_icd.x86_64.json` instead of `nvidia_icd.json`:

```bash
$ ls /nix/store/61cw28zk1s7qfh825ldg8if7x68qfr2r-nvidia-x11-515.48.07-nixGL/share/vulkan/icd.d/
nvidia_icd.x86_64.json
```
